
export const ROObj: any[] = [
    {
        "ReportObjectId": "54603468-de8b-4ed3-8bc9-7758268d2822",
        "ReportObjectName": "Account - Company Code",
        "ObjectGroupName": "Company",
        "isDefault":true,
        "DisplayName": "Account - Company Code",
        "LayoutArea": 0,
        "SequenceNumber": 27,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 1,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 38,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 1,
        "FilterBy": { "field": { "value": "1","title": "Filter by Selection"}},
        // "FilterBy": 1,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterTabInfo": "",
        // "FilterConditionOperator": {"field":{ "title": "Contains", "op": 1 }},
        "FilterConditionOperator": { "title": "Contains", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
            {
              "title": "AFRICA",
              "IsSelected": false
            },
            {
              "title": "ASIA",
              "IsSelected": false
            },
            {
              "title": "EUROPE",
              "IsSelected": false
            },
            {
              "title": "MIDDLE EAST",
              "IsSelected": false
            },
            {
              "title": "NORTH AMERICA",
              "IsSelected": false
            },
            {
              "title": "UNCLASSIFIED",
              "IsSelected": false
            },
            {
              "title": "WEST PACIFIC",
              "IsSelected": false
            }
          ]        
    },
    {
        "ReportObjectId": "d8c44c46-44f6-42c6-8ae1-6b3afdc35088",
        "ReportObjectName": "Business Area",
        "ObjectGroupName": "Spend",
        "DisplayName": "Business Area",
        "LayoutArea": 0,
        "SequenceNumber": 59,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 1,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 13,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 1,
        "FilterBy":{ "field": { "value": "1","title": "Filter by Selection"}},
        // "FilterBy": 1,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterTabInfo": "",
        // "FilterConditionOperator": {"field":{ "title": "Contains", "op": 1 }},
        "FilterConditionOperator": { "title": "Contains", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
            {
              "title": "Business Area",
              "IsSelected": false
            },
            {
              "title": "Business Area 2",
              "IsSelected": false
            },
            {
              "title": " Business Area 3",
              "IsSelected": false
            },
            {
              "title": "MIDDLE EAST",
              "IsSelected": false
            },
            {
              "title": "NORTH AMERICA",
              "IsSelected": false
            },
            {
              "title": "UNCLASSIFIED",
              "IsSelected": false
            },
            {
              "title": "WEST PACIFIC",
              "IsSelected": false
            }
          ]
    },
  {
        "ReportObjectId": "2be0f7fe-05ce-4b55-b765-4906a120a3c3",
        "ReportObjectName": "Transaction Count",
        "ObjectGroupName": "Spend",
        "DisplayName": "Transaction Count",
        "LayoutArea": 0,
        "SequenceNumber": 57,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 0,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 27,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 2,
        "FilterBy": { "field": { "value": "","title": ""}},
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterConditionOperator": { "title": "Greater Than", "op": 1 },
        "FilterConditionValue": {"value":''},
        "FilterConditionText": {"value":''},
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "FilterConditionRangeValue": {
          "from": '',
          "to": ''
        },
    },
      {
        "ReportObjectId": "9c1d186b-6073-4d6c-b14a-272Cb0c2bD2a24",
        "ReportObjectName": "Vendor Count",
        "ObjectGroupName": "Spend",
        "DisplayName": "Vendor Count",
        "LayoutArea": 0,
        "SequenceNumber": 57,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 0,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 27,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0bshy66d07629d",
        "FilterType": 2,
        "FilterBy": { "field": { "value": "","title": ""}},
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-928345g7db6fa",
        "ConfigurationValue": null,
        "FilterConditionOperator": { "title": "Greater Than", "op": 1 },
        "FilterConditionValue": {"value":''},
        "FilterConditionText": {"value":''},
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "FilterConditionRangeValue": {
          "from": '',
          "to": ''
        },
    },
    {
        "ReportObjectId": "60b13727-bec5-4896-8e43-edb422ec6f82",
        "ReportObjectName": "Company City",
        "ObjectGroupName": "Region",
        "DisplayName": "Company City",
        "LayoutArea": 0,
        "SequenceNumber": 42,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 1,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 12,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 1,
        "FilterBy":{ "field": { "value": "1","title": "Filter by Selection"}},
        // "FilterBy": 1,
        "FormatKey": "",
        "ReportObjectWidth": -2147483648,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterTabInfo": "",
        // "FilterConditionOperator": {"field":{ "title": "Contains", "op": 1 }},
        "FilterConditionOperator": { "title": "Contains", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
            {
              "title": "Company City",
              "IsSelected": false
            },
            {
              "title": "Company City 2",
              "IsSelected": false
            },
            {
              "title": "Company City 3",
              "IsSelected": false
            },
            {
              "title": "MIDDLE EAST",
              "IsSelected": false
            },
            {
              "title": "NORTH AMERICA",
              "IsSelected": false
            },
            {
              "title": "UNCLASSIFIED",
              "IsSelected": false
            },
            {
              "title": "WEST PACIFIC",
              "IsSelected": false
            }
          ] 
    },
    {
        "ReportObjectId": "e79777c0-c4c3-47b7-97b2-78e3a71a9cef",
        "ReportObjectName": "Company Country",
        "ObjectGroupName": "Region",
        "DisplayName": "Company Country",
        "LayoutArea": 0,
        "SequenceNumber": 39,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 1,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 9,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 1,
        "FilterBy":{ "field": { "value": "1","title": "Filter by Selection"}},
        // "FilterBy":1,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterTabInfo": "",
        // "FilterConditionOperator": {"field":{ "title": "Contains", "op": 1 }},
        "FilterConditionOperator": { "title": "Contains", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
            {
              "title": "Company Country",
              "IsSelected": false
            },
            {
              "title": "Company Country 2",
              "IsSelected": false
            },
            {
              "title": "Company Country 3",
              "IsSelected": false
            },
            {
              "title": "MIDDLE EAST",
              "IsSelected": false
            },
            {
              "title": "NORTH AMERICA",
              "IsSelected": false
            },
            {
              "title": "UNCLASSIFIED",
              "IsSelected": false
            },
            {
              "title": "WEST PACIFIC",
              "IsSelected": false
            }
          ]
    },
    {
        "ReportObjectId": "323be080-bfd0-4bb3-aaaf-9da0835200d6",
        "ReportObjectName": "Company Level 1",
        "ObjectGroupName": "Company",
        "DisplayName": "Company Level 1",
        "LayoutArea": 0,
        "SequenceNumber": 28,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": false,
        "ReportObjectType": 1,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 6,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 1,
        "FilterBy":{ "field": { "value": "1","title": "Filter by Selection"}},
        // "FilterBy":1,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterTabInfo": "",
        // "FilterConditionOperator": {"field":{ "title": "Contains", "op": 1 }},
        "FilterConditionOperator": { "title": "Contains", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
            {
              "title": "Company Level 1 ",
              "IsSelected": false
            },
            {
              "title": "Company Level 2",
              "IsSelected": false
            },
            {
              "title": "Company Level 3",
              "IsSelected": false
            },
            {
              "title": "MIDDLE EAST",
              "IsSelected": false
            },
            {
              "title": "NORTH AMERICA",
              "IsSelected": false
            },
            {
              "title": "UNCLASSIFIED",
              "IsSelected": false
            },
            {
              "title": "WEST PACIFIC",
              "IsSelected": false
            }
          ] 
    },
    {
      "ReportObjectId": "39233da6-6c0e-4dc2-9d69-f5e4f6dfcfbc",
      "ReportObjectName": "Date - Accounting",
      "ObjectGroupName": "Spend",
      "DisplayName": "Date - Accounting",
      "LayoutArea": 0,
      "SequenceNumber": 78,
      "IsFilterable": false,
      "IsDerived": false,
      "IsTransactional": false,
      "IsSelectAll": true,
      "ReportObjectType": 1,
      "ReportObjectDataType": 6,
      "IsDrillToTransactional": false,
      "DrillTransactionOrder": 76,
      "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
      "FilterType": 4,
      "FormatKey": "",
      "ReportObjectWidth": 150,
      "IsDrill": false,
      "CustomFormula": "",
      "WijmoGridAggregatedType": 0,
      "OpportunityFinder_SequenceNumber": 291,
      "Is_DefaultOpportunityFinder": false,
      "Expression": "",
      "ParentReportObjects": null,
      "Tablename": "",
      "CreatedBy": null,
      "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
      "ConfigurationValue": null,
      "FilterBy":{ "field": { "value": "1","title": "Filter by Dynamic Period"}},
      // "FilterBy":1,
      "FilterSearchText": { "value":''},
      "FilterConditionText": {"value":''},
      "FilterTabInfo": "",
      // "FilterConditionOperator": {"field":{ "title": "Is", "op": 3 }},
      "FilterConditionOperator": { "title": "Is", "op": 3 },
      "PartialSelect": false,
      "IsShowSelected":false,
      "filterSelSet": false,
      "selectAllTxt": "All",
      "selectAll": false,
      "SelectAll":false,
      "selectedFilterList": [],
      "inChip":false,
      "filterCdnSet": false,
      "filterValueSet": false,
      "FilterConditionValue":  { "value": ''},
      "RollingDateModel" : {"value":''} ,
      "NextDateModel": {"value":''},
      "currentdateModel": {"value":''},
      "FilterConditionRangeValue": {
        "from": 1511461799000,
        "to": 1511461799000
      },
      "FilterRadioOperator":{ "field": { "op": "2", "title": "Today" }},
  },
  {
    "ReportObjectId": "c8a9d038-095f-4e96-8cfd-b48fc039df72",
    "ReportObjectName": "Payment Date",
    "ObjectGroupName": "Spend",
    "DisplayName": "Payment Date",
    "LayoutArea": 0,
    "SequenceNumber": 67,
    "IsFilterable": false,
    "IsDerived": false,
    "IsTransactional": false,
    "IsSelectAll": true,
    "ReportObjectType": 1,
    "ReportObjectDataType": 6,
    "IsDrillToTransactional": false,
    "DrillTransactionOrder": 25,
    "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    "FilterType": 4,
    "FormatKey": "",
    "ReportObjectWidth": 150,
    "IsDrill": false,
    "CustomFormula": "",
    "WijmoGridAggregatedType": 0,
    "OpportunityFinder_SequenceNumber": 291,
    "Is_DefaultOpportunityFinder": false,
    "Expression": "",
    "ParentReportObjects": null,
    "Tablename": "",
    "CreatedBy": null,
    "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    "ConfigurationValue": null,
    "FilterBy":{ "field": { "value": "1","title": "Filter by Dynamic Period"}},
    // "FilterBy":1,
    "FilterSearchText": { "value":''},
    "FilterConditionText": {"value":''},
    "FilterTabInfo": "",
    // "FilterConditionOperator": {"field":{ "title": "Is", "op": 3 }},
    "FilterConditionOperator": { "title": "Is", "op": 3 },
    "PartialSelect": false,
    "IsShowSelected":false,
    "filterSelSet": false,
    "selectAllTxt": "All",
    "selectAll": false,
    "SelectAll":false,
    "selectedFilterList": [],
    "inChip":false,
    "filterCdnSet": false,
    "filterValueSet": false,
    "FilterConditionValue": { "value": ''},
    "RollingDateModel" : {"value":''} ,
    "NextDateModel": {"value":''},
    "currentdateModel": {"value":''},
    "FilterConditionRangeValue": {
      "from": 1511461799000,
      "to": 1511461799000
    },
    "FilterRadioOperator":{ "field": { "op": "2", "title": "Today" }}    
},
    {
        "ReportObjectId": "cbcb59c3-9872-41f4-8842-8e98d167574c",
        "ReportObjectName": "Invoice Unit Price",
        "ObjectGroupName": "Spend",
        "DisplayName": "Invoice Unit Price",
        "LayoutArea": 0,
        "SequenceNumber": 64,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 0,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 48,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 10,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterSearchValue": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterConditionValue": { "value": ''},
        "FilterConditionRangeValue": {
          "from": '',
          "to": ''
        },
        "FilterBy":{ "field": { "value": "2","title": "Filter by Condition"}},
        "FilterConditionOperator": { "title": "Greater Than", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
          {
            "title": "1",
            "IsSelected": false
          },
          {
            "title": "2",
            "IsSelected": false
          },
          {
            "title": "3",
            "IsSelected": false
          },
          {
            "title": "4",
            "IsSelected": false
          },
          {
            "title": "5",
            "IsSelected": false
          },
          {
            "title": "6",
            "IsSelected": false
          },
          {
            "title": "8",
            "IsSelected": false
          }
        ]
    },
    {
        "ReportObjectId": "c27aac11-5d2b-41f8-b67f-e6388d5b5642",
        "ReportObjectName": "Direct Ship Flag",
        "ObjectGroupName": "Spend",
        "DisplayName": "Direct Ship Flag",
        "LayoutArea": 0,
        "SequenceNumber": 75,
        "IsFilterable": false,
        "IsDerived": false,
        "IsTransactional": false,
        "IsSelectAll": true,
        "ReportObjectType": 0,
        "ReportObjectDataType": 0,
        "IsDrillToTransactional": false,
        "DrillTransactionOrder": 70,
        "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
        "FilterType": 10,
        "FormatKey": "",
        "ReportObjectWidth": 150,
        "IsDrill": false,
        "CustomFormula": "",
        "WijmoGridAggregatedType": 0,
        "OpportunityFinder_SequenceNumber": 291,
        "Is_DefaultOpportunityFinder": false,
        "Expression": "",
        "ParentReportObjects": null,
        "Tablename": "",
        "CreatedBy": null,
        "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
        "ConfigurationValue": null,
        "FilterSearchText": { "value":''},
        "FilterSearchValue": { "value":''},
        "FilterConditionText": {"value":''},
        "FilterConditionValue": { "value": ''},
        "FilterConditionRangeValue": {
          "from": '',
          "to": ''
        },
        "FilterBy":{ "field": { "value": "2","title": "Filter by Condition"}},
        "FilterConditionOperator": { "title": "Greater Than", "op": 1 },
        "PartialSelect": false,
        "IsShowSelected":false,
        "filterSelSet": false,
        "selectAllTxt": "All",
        "selectAll": false,
        "SelectAll":false,
        "selectedFilterList": [],
        "inChip":false,
        "filterCdnSet": false,
        "filterValueSet": false,
        "filteredList":[],
        "FilterList": [
          {
            "title": "1.0",
            "IsSelected": false
          },
          {
            "title": "2.0",
            "IsSelected": false
          },
          {
            "title": "3.0",
            "IsSelected": false
          },
          {
            "title": "4.44",
            "IsSelected": false
          },
          {
            "title": "5.45",
            "IsSelected": false
          },
          {
            "title": "6",
            "IsSelected": false
          },
          {
            "title": "8",
            "IsSelected": false
          }
        ] 
    },
    // {
    //     "ReportObjectId": "8616d5a6-7434-44f6-829a-9510b5789737",
    //     "ReportObjectName": "DNB Average Score",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "DNB Average Score",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 65,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 49,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "2d1513a4-10e2-4f7c-97b8-d728ef391b6d",
    //     "ReportObjectName": "DNB FSS",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "DNB FSS",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 70,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 65,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "08996710-711c-4266-a362-14b1969c32ac",
    //     "ReportObjectName": "DNB Risk Flag",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "DNB Risk Flag",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 45,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 6,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "eb8d0fea-8989-4525-8f9e-f5833473f28d",
    //     "ReportObjectName": "DNB SER",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "DNB SER",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 77,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 75,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "a720a708-af8c-4d01-8ffd-81f3d83a17ba",
    //     "ReportObjectName": "DNB SSI",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "DNB SSI",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 63,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 44,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "ea62cd9e-fa64-45c5-a114-0c425eeb0bce",
    //     "ReportObjectName": "ERP Commodity - Invoice ",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "ERP Commodity - Invoice ",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 44,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 29,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "d10f4298-1a08-4379-afb0-352730eccfa8",
    //     "ReportObjectName": "ERP Commodity - PO",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "ERP Commodity - PO",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 51,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 28,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "95fe94b8-6ee8-44ac-bb0c-dd48f5b8c155",
    //     "ReportObjectName": "ERP Commodity Code - Invoice",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "ERP Commodity Code - Invoice",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 73,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 68,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "87a24518-b5cb-4c35-911c-78f9eeab267d",
    //     "ReportObjectName": "Foreign Spend Flag",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Foreign Spend Flag",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 61,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 40,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "36085fa4-1257-4421-b9f6-2c1ef90c821d",
    //     "ReportObjectName": "GL Account",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "GL Account",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 49,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 31,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "8e4faeff-24c0-4a30-9c07-21a2ca22c6ef",
    //     "ReportObjectName": "GL Account Code",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "GL Account Code",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 47,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 9,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "b8a9391f-95e2-4797-98b4-70e7b3bb58e9",
    //     "ReportObjectName": "INCO Code",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "INCO Code",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 60,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 34,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "5ee20615-c77f-4ba8-a2df-7cae869faa03",
    //     "ReportObjectName": "INCO Terms",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "INCO Terms",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 62,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 41,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "ecd66c6b-1492-43aa-8197-be2c0d9e0f63",
    //     "ReportObjectName": "Invoice Date",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Invoice Date",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 68,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 6,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 26,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "df6bc806-6fb8-4cac-960f-681933bc0c0d",
    //     "ReportObjectName": "Level 1 Category",
    //     "ObjectGroupName": "Category",
    //     "DisplayName": "Level 1 Category",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 20,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 1,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "2b19dedc-189d-40ae-b2a2-ee1c4d017eb2",
    //     "ReportObjectName": "Level 2 Category",
    //     "ObjectGroupName": "Category",
    //     "DisplayName": "Level 2 Category",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 23,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 2,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "5b54df6f-0e08-4378-886f-d1084ae575be",
    //     "ReportObjectName": "Level 3 Category",
    //     "ObjectGroupName": "Category",
    //     "DisplayName": "Level 3 Category",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 22,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 3,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "1a68b487-5e50-4bc1-be0b-a0a11e6af57c",
    //     "ReportObjectName": "Level 4 Category",
    //     "ObjectGroupName": "Category",
    //     "DisplayName": "Level 4 Category",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 4,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": true,
    //     "DrillTransactionOrder": 4,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 4,
    //     "Is_DefaultOpportunityFinder": true,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "f8e587ed-2ec1-4db6-85d0-604b8ddd803b",
    //     "ReportObjectName": "Level 5 Category",
    //     "ObjectGroupName": "Category",
    //     "DisplayName": "Level 5 Category",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 19,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 5,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "f09bbdf6-ab72-4845-b05b-43c0c65c3d70",
    //     "ReportObjectName": "Major Account",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Major Account",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 56,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 25,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "c05c2574-be2e-4dc6-8856-3838d050fef2",
    //     "ReportObjectName": "Masco- Supplier Country",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Masco- Supplier Country",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 55,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 17,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "5d8785d5-c4f9-49f8-99ec-f736cb76b6e2",
    //     "ReportObjectName": "Masco- Supplier Region",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Masco- Supplier Region",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 69,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 77,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "b4081d21-2181-4cf1-92f1-e2e135083fbb",
    //     "ReportObjectName": "Original Currency Code",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Original Currency Code",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 74,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 69,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "78ad1e5e-8ad8-420a-a230-23afe1dd7704",
    //     "ReportObjectName": "Part Country - Invoice",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Part Country - Invoice",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 48,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 30,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "0f90de33-d307-4bef-b60a-da7a1aeb902c",
    //     "ReportObjectName": "Part Country-PO",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Part Country-PO",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 71,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 66,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "370c53ad-6b9e-4513-93e3-3b387e51c641",
    //     "ReportObjectName": "Payment Discount Days – Supplier",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Discount Days – Supplier",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 56,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 19,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "ac072393-8c02-4148-a264-82613f6aa115",
    //     "ReportObjectName": "Payment Discount-Supplier",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Discount-Supplier",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 64,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 46,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "67e4a072-c4a5-469d-92b9-0449861753f6",
    //     "ReportObjectName": "Payment Net Days – Supplier",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Net Days – Supplier",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 52,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 3,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "c3435ba9-60c2-4962-8fd1-40e3039550c5",
    //     "ReportObjectName": "Payment Term - Invoice ",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Payment Term - Invoice ",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 55,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 33,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "a383b629-b78c-4fdd-9ca1-35df561b38e1",
    //     "ReportObjectName": "Payment Term - Invoice ERP",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Payment Term - Invoice ERP",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 52,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 32,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "9b354393-4b80-440b-a391-81b1a705d397",
    //     "ReportObjectName": "Payment Term - Supplier",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Term - Supplier",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 63,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 43,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "a5266b43-c2f0-4200-a9f0-4140d310741b",
    //     "ReportObjectName": "Payment Term - Supplier ERP",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Term - Supplier ERP",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 57,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 22,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "db90b3f1-9b0a-4ced-81b4-ea455485abf9",
    //     "ReportObjectName": "Payment Term Code - Invoice ",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Payment Term Code - Invoice ",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 76,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 71,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "3ad28cdf-a0be-4390-92d5-b91b74350ba1",
    //     "ReportObjectName": "Payment Term Code - Supplier ",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Term Code - Supplier ",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 67,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 59,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "4c8fabee-b78d-4c17-9ca9-cabd01fe7791",
    //     "ReportObjectName": "Payment Term Type - Supplier",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Payment Term Type - Supplier",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 68,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 63,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "beba5988-3f41-4065-bc13-b02248c2b12f",
    //     "ReportObjectName": "Payment Type",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Payment Type",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 66,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 24,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "df26e7a6-cd2a-4e0e-85c4-18bc42bb8267",
    //     "ReportObjectName": "PO Flag",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "PO Flag",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 46,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 7,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "e61e8333-3119-4902-a8b8-3a2f510db23d",
    //     "ReportObjectName": "Rolling 4 Qtrs",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Rolling 4 Qtrs",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 53,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 18,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "425f34b0-3075-4aed-a3b7-c0e2344822d1",
    //     "ReportObjectName": "Source System",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Source System",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 69,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 14,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "36b59d35-e429-4e54-b50a-3d10d660188c",
    //     "ReportObjectName": "Spend Bucket Flag",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "Spend Bucket Flag",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 54,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 20,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "49e1adc3-09a0-4767-b854-7d75c1b0c3a8",
    //     "ReportObjectName": "Supplier - LocationId",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier - LocationId",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 62,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 42,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "7f82e377-700c-4d54-be97-73870f1d525b",
    //     "ReportObjectName": "Supplier - Normalized",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier - Normalized",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 2,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 17,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 2,
    //     "Is_DefaultOpportunityFinder": true,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "05507fd1-085d-45e6-94ab-a8c1f661c456",
    //     "ReportObjectName": "Supplier - Parent",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier - Parent",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 66,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 15,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "c965ee7c-c582-4a28-b327-03e5cea07930",
    //     "ReportObjectName": "Supplier City",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier City",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 51,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 23,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "7022acf8-b0d6-4e1e-b8b3-2ed6ad50408e",
    //     "ReportObjectName": "Supplier Country",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier Country",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 54,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 20,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "d59fa730-b00d-4a44-917b-6abc3e84bbb2",
    //     "ReportObjectName": "Supplier DUNS Number",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier DUNS Number",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 60,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 18,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "9d7345e3-9c71-46db-ab2d-02d54b1fb1ce",
    //     "ReportObjectName": "Supplier Name - ERP",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier Name - ERP",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 1,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": true,
    //     "DrillTransactionOrder": 16,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 1,
    //     "Is_DefaultOpportunityFinder": true,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "532bf974-4deb-4e9d-8e3b-95353a250716",
    //     "ReportObjectName": "Supplier Number",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier Number",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 65,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 50,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "e7b4d5b4-a38f-41d2-88ab-201cbd79d377",
    //     "ReportObjectName": "Supplier Region",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier Region",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 53,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 21,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "7e26ef55-0bdc-4261-8138-42bcf3e8eb44",
    //     "ReportObjectName": "Supplier State",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier State",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 58,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 22,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "0707d353-b17a-4621-8751-44c6b9229a84",
    //     "ReportObjectName": "Supplier Type",
    //     "ObjectGroupName": "Supplier",
    //     "DisplayName": "Supplier Type",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 59,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": true,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 19,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "665b0ed6-4210-479e-8589-60e5456d1d04",
    //     "ReportObjectName": "User - Invoice ",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "User - Invoice ",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 58,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 27,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // },
    // {
    //     "ReportObjectId": "e317780d-2d31-4879-bd21-30828f408316",
    //     "ReportObjectName": "User - PO",
    //     "ObjectGroupName": "Spend",
    //     "DisplayName": "User - PO",
    //     "LayoutArea": 0,
    //     "SequenceNumber": 50,
    //     "IsFilterable": false,
    //     "IsDerived": false,
    //     "IsTransactional": false,
    //     "IsSelectAll": false,
    //     "ReportObjectType": 1,
    //     "ReportObjectDataType": 0,
    //     "IsDrillToTransactional": false,
    //     "DrillTransactionOrder": 14,
    //     "FilterTypeObjectId": "10efc3f0-7ec5-4d8f-b6da-0b476d07629d",
    //     "FilterType": 1,
    //     "FormatKey": "",
    //     "ReportObjectWidth": 150,
    //     "IsDrill": false,
    //     "CustomFormula": "",
    //     "WijmoGridAggregatedType": 0,
    //     "OpportunityFinder_SequenceNumber": 291,
    //     "Is_DefaultOpportunityFinder": false,
    //     "Expression": "",
    //     "ParentReportObjects": null,
    //     "Tablename": "",
    //     "CreatedBy": null,
    //     "DataSource_ObjectId": "a9bf1050-6c9e-483f-9cac-92895b7db6fa",
    //     "ConfigurationValue": null
    // }
];
