var userInfo = {
  "APIMBaseURL": "https://api-smartdev.gep.com/",
  "RegionID":"15",  
  "DocumentUrl": null,
  "UserBasicDetails": {
    "ClientName": "Chevron",
    "UserId": 479054,
    "ContactCode": 1466240040000001,
    "LoggerCode": "EC101",
    "EntityId": 0,
    "EntityType": "",
    "Product": 9,
    "Culture": "en-US",
    "UserName": "Sachin Mishra",
    "Contexts": [],
    "CompanyName": "BuyerSqlConn",
    "ClientID": 538858,
    "BuyerPartnerCode": 70021704,
    "IsAdmin": false,
    "IsSupplier": true,
    "IsSuperUser": false,
    "DefaultCurrencyCode": "",
    "BelongingEntityId": 0,
    "BelongingEntityDetailCode": 0,
    "ServingEntityId": 0,
    "ServingEntityDetailCode": 0,
    "ShipToLocationId": 0
  },
  "UserPreferences": {     
    "EncryptedBPC":"MTg5NTE10",
    "WijmoLicenseKey": "GEP,smart.gep.com|eu.smart.gep.com|smartuateu.gep.com|smartstg.gep.com|smartuatstaging.gep.com|smartuat.gep.com|smartqc.gep.com|smartdev.gep.com,549554169121377#B0HIJ94QiwiI7czMxITM9YTM4UTN9QTNiojIklkIs4nIxYHOxAjMiojIyVmdiwSZzxWYmpjIyNHZisnOiwmbBJye0ICRiwiI34zZBdzK9okbvdUToJjc7gjW7Y7N4hXb92iMlZnTopEdwJHayh4VRtyYIR5QPt4VkpkYJJkNRREdyZ5LrdFNRNkN0Bla7kmWoJ5RONjeI9mbR34UoR6QZl4U9tSauJmd5wWetZ4Ku3iRJpVQ5cme4AjcwVDbORlMhJHNhhHVMJjUyB5VyIGc6pnYKpldsZ4bndzM4Z4ZrRjYPFES7lUVmhUQ5oFMTlkTEFDVnlGSyQmVLZ5ZQdHUOdmRSZWVJVWRt3ydXZzRvMnT4VmRp5EU8sUOqd4UYZ4aKJ5URRlZChXNwdjZ9NGdylFWH5GWx2SaoJGTvIWQQFWarplN4k7LiVWUpBzKUJ5aPR6NEJke9ole9lzUCt4YrNFMxUVRBVEdxgmMQFGWIhEVs94b4gTMUd6VXJTcO54LQhDdG3GZCd4R7wkRrQmMvoUMO9UaixUbwIFNXVnYtNmI0IyUiwiI9M4M4EEM4EjI0ICSiwSOwYjM7ITO6cTM0IicfJye35XX3JSSwIjUiojIDJCLi86bpNnblRHeFBCI4VWZoNFelxmRg2Wbql6ViojIOJyes4nI5kkTRJiOiMkIsIibvl6cuVGd8VEIgIXZ7VWaWRncvBXZSBybtpWaXJiOi8kI1xSfis4N8gkI0IyQiwiIu3Waz9WZ4hXRgAydvJVa4xWdNBybtpWaXJiOi8kI1xSfiQjR6QkI0IyQiwiIu3Waz9WZ4hXRgACUBx4TgAybtpWaXJiOi8kI1xSfiMzQwIkI0IyQiwiIlJ7bDBybtpWaXJiOi8kI1xSfiUFO7EkI0IyQiwiIu3Waz9WZ4hXRgACdyFGaDxWYpNmbh9WaGBybtpWaXJiOi8kI1tlOiQmcQJCLiQzM4UTMwASNyATM8EDMyIiOiQncDJCLi46bj9CcldmL6VGZ4JXYtNHLt36YuAXZn9yYxRnch56cs46bj9CcldmL4FWd4JXYtNHLt36YuAXZn9yZul6ZhR7c4FWd4JXYtNHLt36YuAXZn9yZ4NHdyFWbzxSbvNmLwV6ZuUXZ4FWd4JXYtNHLt36YuAXZn9CdyFWbz9SdlxSbvNmLwV6ZuQnch56ciojIz5GRiwiIQVIR3o",
    "PreferenceId": 17,
    "ContactCode": 1466240040000001,
    "UserPreferenceDetails": {
      "Bookmark": [],
      "Favorite": [],
      "LastLoginDate": "0001-01-01T00:00:00",
      "LastloginURL": null,
      "CreateList": null,
      "SnifferDismiss": true
    },
    "UserPreferenceFields": {
      "DocTypeAttributes": [{
        "DocType": 8,
        "FieldAttributes": [{
          "FieldName": "OrderInvoicingStatus",
          "IsVisible": true
        }, {
          "FieldName": "OrderNumber",
          "IsVisible": true
        }, {
          "FieldName": "NeedByDate",
          "IsVisible": true
        }, {
          "FieldName": "OrderContact",
          "IsVisible": true
        }, {
          "FieldName": "Category",
          "IsVisible": true
        }, {
          "FieldName": "CreatedBetween",
          "IsVisible": true
        }, {
          "FieldName": "Ship-ToLocation",
          "IsVisible": true
        }, {
          "FieldName": "Amount",
          "IsVisible": true
        }, {
          "FieldName": "IncludeClosedOrders",
          "IsVisible": true
        }, {
          "FieldName": "Author",
          "IsVisible": true
        }, {
          "FieldName": "OrdersWithUrgentRequisition",
          "IsVisible": true
        }, {
          "FieldName": "OrderReceivingStatus",
          "IsVisible": true
        }, {
          "FieldName": "ItemNumber",
          "IsVisible": true
        }, {
          "FieldName": "SupplierItemNumber",
          "IsVisible": true
        }, {
          "FieldName": "OrderName",
          "IsVisible": true
        }]
      }]
    },
    "UserBasicDetails": {
      "ContactCode": 1466240040000001
    }
  },
  "NAVButtonsAccessRights": {
    "Task": null,
    "Manage": null,
    "Create": null,
    "Analyze": null,
    "IntExtAnn": {
      "mInt": false,
      "mExt": false
    },
    "IsCatalogAdmin": false
  },
  "Activities": ["10600030", "10600031", "10100002", "10300008", "10300048", "10300049", "10300050", "10300065", "10400001", "10500030", "10500031", "10700005", "10700014", "10700034", "10700041", "10700042", "10700043", "10700044", "10700045", "10700048", "10700049", "10700050", "10700052", "10700070", "10700071", "10700078", "10700082", "10700083", "10700084", "21600007", "21600012"],
  "SessionGuid": "5bb32f6c-8988-4812-ac40-44245e5f86c7",
  "TenantName": "Chevron",
  "URLs": {
    "AppURL": "https://smartdev.gep.com/",
    //"AppURL": "http://127.0.0.1:81/",
    "ContentURL": "http://localhost/gepdevmtstorage/",
    "GePServiceURL": "https://smartdev.gep.com/",
    //"BaseURL": "http://127.0.0.1:81/",
    "BaseURL": "https://gepqcsmart-rest.gep.com/",
    "NodeServiceURL": "https://smartbydev.gep.com/api/",
    "P2PRestURL": "https://gepqcsmart-relay.servicebus.windows.net/",
    "GePBlobContentURL": null,
    "ApimURL": null,
    "SignalRUrl": null,
    "APIBaseURL": "https://api-smartdev.gep.com/",
    "SCLandingPage": "https://smartdev.gep.com/Smart",
    "ServiceURL": "https://smartdev.gep.com/",
    "WorkspaceBaseUrl":"https://smartdev.gep.com/",
  },
  "CompanyAddress": {
    "AddressCode": 0,
    "Addressline1": null,
    "Addressline2": null,
    "Addressline3": null,
    "City": null,
    "ZipCode": null,
    "StateInfo": {
      "StateCode": 0,
      "StateName": null,
      "CountryId": 0,
      "IsActive": true,
      "IsDeleted": false,
      "StateAbbrevationCode": null,
      "StateOther": null,
      "CompanyName": null,
      "ClientID": 0,
      "PageIndex": 0,
      "PageSize": 0,
      "TotalRecords": 0,
      "SortBy": null,
      "SortOrder": null,
      "CultureCode": "en-US",
      "CreatedOn": "0001-01-01T00:00:00",
      "UpdatedOn": "0001-01-01T00:00:00",
      "CreatedBy": 0,
      "ModifiedBy": 0,
      "DefaultCurrencyCode": null
    },
    "CountryInfo": {
      "CountryId": 0,
      "CountryCode": null,
      "CountryName": null,
      "CountryCultureInfo": null,
      "CurrencyCode": null,
      "IsActive": true,
      "IsDeleted": false,
      "PreferenceOrder": 0,
      "CompanyName": null,
      "ClientID": 0,
      "PageIndex": 0,
      "PageSize": 0,
      "TotalRecords": 0,
      "SortBy": null,
      "SortOrder": null,
      "CultureCode": "en-US",
      "CreatedOn": "0001-01-01T00:00:00",
      "UpdatedOn": "0001-01-01T00:00:00",
      "CreatedBy": 0,
      "ModifiedBy": 0,
      "DefaultCurrencyCode": null
    },
    "PhoneNo1": null,
    "ExtenstionNo1": null,
    "PhoneNo2": null,
    "ExtenstionNo2": null,
    "MobileNo": null,
    "FaxNo": null,
    "GeographyDetail": null,
    "Latitude": null,
    "Longitude": null,
    "County": null,
    "CompanyName": null,
    "ClientID": 0,
    "PageIndex": 0,
    "PageSize": 0,
    "TotalRecords": 0,
    "SortBy": null,
    "SortOrder": null,
    "CultureCode": "en-US",
    "CreatedOn": "0001-01-01T00:00:00",
    "UpdatedOn": "0001-01-01T00:00:00",
    "CreatedBy": 0,
    "ModifiedBy": 0,
    "DefaultCurrencyCode": null
  },
  "UserTheme": "greenTheme",
  "AreaName": "P2P",
  "Redirect1Documentsto2": false,
  "EncryptedBPC": "NzAwMjE3MDQ1",
  "SessionTimeoutInterval": 120,
  "FullName": "Chevron Supplier .",
  "DocumentSettings": null,
  "CommonSettings": {
    "ContactTypeInfo": 1,
    "SettingConfigurationId": 12,
    "SettingDetailsId": 11,
    "ContactCode": -9223372036854775808,
    "ObjectTypes": null,
    "lstSettings": [{
      "DefaultValue": "2",
      "FieldName": "MinPrecessionValue",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "MaxPrecessionValue",
      "FieldValue": "6",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowAdhocShipToLocation",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowAdhocShipToForFutureReference",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowTaxExempt",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "LOC",
      "FieldName": "LocationPrefix",
      "FieldValue": "LOC",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "1",
      "FieldName": "CategorySelectionLevel",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowOneShipToLocation",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "PartnerStatuses",
      "FieldValue": "6",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "ERPOrderTypeVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "WorkOrderNoVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "DefaultMaterialTaxExempt",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "DefaultServiceTaxExempt",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowCommentsAndAttachments",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "BillableFieldAvailable",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowNonPrimaryPartnerForItem",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "ToRestrictBuyerCreatePOFromOwnReq",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsInventoryTypeVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "CodeCombinationFieldId",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "CodeCombinationFieldValue",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowToCreateSplits",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowPaymentTermsEdit",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowCreateScanInvoice",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "10",
      "FieldName": "EntityMappedToBillToLocation",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowOtherCharges",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "GetUserMappedEntities",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "AllowResetChildEntities",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "CapitalizedFieldAvailable",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "CapitalCodeNoVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "MaxPrecessionValueforTotal",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "AccessTypeForComment",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowDefaultCategory",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "10",
      "FieldName": "MaterialServiceExpandCollapseBehaviour",
      "FieldValue": "10",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsBillableFieldMandatory",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowDeliverToFreeText",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsPOSignatoryMandatory",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsPOSignatoryDefault",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "TRUE",
      "FieldName": "PopulateDefaultNeedByDate",
      "FieldValue": "TRUE",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "1",
      "FieldName": "AllowNegativeValues",
      "FieldValue": "1",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "TRUE",
      "FieldName": "IsLineNumberVisible",
      "FieldValue": "TRUE",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsProgramEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "FALSE",
      "FieldName": "IsSendBackPostApproval",
      "FieldValue": "FALSE",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "Header",
      "FieldName": "MatchTypeLevel",
      "FieldValue": "Header",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "MatchTypeForMaterial",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "1",
      "FieldName": "MatchTypeForService",
      "FieldValue": "1",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "CheckIsDirect",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsPartnerContactBasedOnOrderingLocations",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "FALSE",
      "FieldName": "LimitAccessControlEntity",
      "FieldValue": "FALSE",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "EA",
      "FieldName": "DefaultUOMforMaterialItem",
      "FieldValue": "EA|Each",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "EA",
      "FieldName": "DefaultUOMforFixedItem",
      "FieldValue": "C62|Activity Unit",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "EA",
      "FieldName": "DefaultUOMforVariableItem",
      "FieldValue": "C62|AU",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsOperationalBudgetEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "Rejected due to insufficient funds availability.",
      "FieldName": "AutoRejectDocumentBudgetValidationComments",
      "FieldValue": "Rejected due to insufficient funds availability.",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "3",
      "FieldName": "ItemDetailsDefaultTab",
      "FieldValue": "3",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "false",
      "FieldName": "GetPartnerSpecificPaymentTerm",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "false",
      "FieldName": "AllowAsyncMethods",
      "FieldValue": "false",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowPaymentTermsEditNonPO",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsZipCodeFormatEnabledforUS",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "EnableMaterialReceiving",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowMultipleManufacturers",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "EnableLogging",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "ContractUtilizationTracking",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "ContractUtilizationTrackingIncludeTaxes",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "TemplateTypePreference",
      "FieldValue": "3",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "MaxPrecessionValueForTaxesAndCharges",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsServiceProcurementEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "AllowSupplierCard",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsVATBasedOnOrderingLocation",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "15",
      "FieldName": "NeedByDateByDays",
      "FieldValue": "15",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityMappedToShippingMethods",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityMappedToPaymentTermsAndCondition",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "FetchDocumentsFromElasticSearch",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityMappedToShipToLocation",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "ShowNeedBydateConfirmation",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowBudgetValidationOnOverAll",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsValidateContractNumber",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsOrderingLocationMandatory",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "true",
      "FieldName": "UpdateTaxOnPunchoutItem",
      "FieldValue": "true",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "true",
      "FieldName": "CommentsCountRequired",
      "FieldValue": "true",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "SupplierRelationshipTypesToBeRestricted",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "None",
      "FieldName": "IsRestrictCurrencyList",
      "FieldValue": "Supplier",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityMappedToOrderTolerance",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "PartnerMappedOrgEntityId",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsAutoSourcing",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForUnitPrice",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "Decimal_MaxPrecessionForUnitPrice",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForQuantity",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "Decimal_MaxPrecessionForQuantity",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForShippingOrFreight",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "Decimal_MaxPrecessionForShippingOrFreight",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForOtherCharges",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "Decimal_MaxPrecessionForOtherCharges",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForContractValue",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "4",
      "FieldName": "Decimal_MaxPrecessionForContractValue",
      "FieldValue": "4",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForTaxesAndCharges",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "Decimal_MinPrecessionForTotalField",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "AccountingDetailVisibiltyInExportPDF",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "AllowCopyAccountingByRatio",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityMappedToPaymentTerms",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsCreatorAllowedAsApprover",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "AllowApproverMultipleLevel",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsSourceSystemVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "1",
      "FieldName": "AllowFilteronApprovers",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "ApprovalFliterEntityTypeId",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "The Document Contains following Accounting Details",
      "FieldName": "NotificationTemplateMessageString",
      "FieldValue": "This Document has the following Entities",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "TaxesVisibleToSupplier",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsBudgetIdVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsTypeOfItemVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsUIResponsive",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsDefaultBudgetStructureEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "InvoiceInterfaceToBuyerERP",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsLinkedLocationEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "RestrictChargeTypesOnPOInvoiceForSupplier",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "1",
      "FieldName": "AccountingSplitMode",
      "FieldValue": "1",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "20",
      "FieldName": "AllowMaxInvoicestoExporttoPDF",
      "FieldValue": "200",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "ClientSettingForExport",
      "FieldValue": "40|Times New Roman,Malgun Gothic,FangSong|0|1",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "ShowBillableAtHeader",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "HeaderLevelBillableMandatory",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "EnablePastDateDocProcess",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "25",
      "FieldName": "AllowPOCloseStatus",
      "FieldValue": "25,41",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "AccessControlOnBudgetAllocation",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "ContractDocumentStatuses",
      "FieldValue": "71,83",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsRequisitionTypeEnabled",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsCreateOnBehalfOfRequisitonAllowed",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "31",
      "FieldName": "EntityMappedWithBuyerAssignee",
      "FieldValue": "31",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "PrimeRevenueExceptionType",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "FALSE",
      "FieldName": "EnableAssigningBuyerToRequisitions",
      "FieldValue": "FALSE",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "22,61",
      "FieldName": "RequisitionStatusForBuyerAssignment",
      "FieldValue": "22,61",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "AllowCustomLablesforExceptions",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "false",
      "FieldName": "IsEnableADRRules",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "false",
      "FieldName": "IsEnableOldADRRules",
      "FieldValue": "true",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsOperationalbudgetPopupEnable",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsHeaderEntitiesNonEditable",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "7",
      "FieldName": "EntityIdMappedToNumberConfiguration",
      "FieldValue": "7",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "IsDefaultOrderingLocation",
      "FieldValue": "True",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "2",
      "FieldName": "INCOTERMS_CODE_DISPLAY",
      "FieldValue": "2",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "Popup",
      "FieldName": "ConfirmationMessageType",
      "FieldValue": "Popup",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "ActivityCodesToSearchOrderContact",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "AllowAcceptorAsApprover",
      "FieldValue": "false",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "RestrictUserMappedCategorySelection",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "CaptureMandatoryWithdrawalComments",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsShipFromLocationMandatory",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "ShipFromLocationType",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "IsShipFromLocationVisible",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "EmailNotificationAccountingEntities",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "False",
      "FieldName": "EnableAdhocApprovalOnly",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "0",
      "FieldName": "PaymentDateDefaultingCriteria",
      "FieldValue": "0",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "",
      "FieldName": "AccountingEntityRelevantForApproval",
      "FieldValue": "",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "false",
      "FieldName": "SendSecureMailAction",
      "FieldValue": "false",
      "OwnerTypeInfo": 2
    }, {
      "DefaultValue": "True",
      "FieldName": "EnableStockReservationViaExternalInventoryIntegration",
      "FieldValue": "False",
      "OwnerTypeInfo": 2
    }],
    "CompanyName": null,
    "ClientID": 0,
    "PageIndex": 0,
    "PageSize": 0,
    "TotalRecords": 0,
    "SortBy": null,
    "SortOrder": null,
    "CultureCode": "en-US",
    "CreatedOn": "0001-01-01T00:00:00",
    "UpdatedOn": "0001-01-01T00:00:00",
    "CreatedBy": 0,
    "ModifiedBy": 0,
    "DefaultCurrencyCode": null
  },
  "Smart1PortalURL": "https://smartdev.gep.com/Portal/Dashboard/Documents?md=bT0xMyZzbT0xNQ2&dd=YnBjPTcwMDIxNzA0JmNjPTUzODg1ODA0MDAwMDAx0&oloc=101",
  "RequestAccess": null,
  "constantURLAndQueryStringValue": {
    "portalURL": "https://smartqc.gep.com/",
    "partnerURL": "https://smartqc.gep.com/",
    "contractURL": "https://smartqc.gep.com/",
    "homeQueryString": "md=bT0x0",
    "catalogQueryString": "md=bT0xMyZzbT0xNA2",
    "orderQueryString": "md=bT0xMyZzbT0xNg2",
    "invoiceQueryString": "md=bT0xMyZzbT0xOA2",
    "receiptQueryString": "md=bT0xMyZzbT0xNw2",
    "requisitionQueryString": "md=bT0xMyZzbT0xNQ2",
    "rfxQueryString": "md=bT0yJnNtPTQ1",
    "auctionQueryString": "md=bT0yJnNtPTU1",
    "partnersQueryString": "md=bT0xOQ2",
    "workBenchQueryString": "md=bT0yJnNtPTg1",
    "contractQueryString": "md=bT0yJnNtPTY1",
    "invoiceReconcillationQueryString": "md=bT0xMyZzbT0zMA2",
    "documentTypeCodes": "101",
    "partnerdocumentTypeCodes": "105",
    "formQueryString": "md=bT0yJnNtPTI40",
    "assessmentQueryString": "md=bT0yJnNtPTc1",
    "auctionRequestQueryString": "md=bT0zMSZzbT0zNA2",
    "contractRequestQueryString": "md=bT0zMSZzbT0zMg2",
    "paymentRequestQueryString": "md=bT0zMSZzbT00Nw2",
    "rfxRequestQueryString": "md=bT0zMSZzbT0zMw2",
    "projectQueryString": "md=bT0zNQ2",
    "creditMemoQueryString": "md=bT0xMyZzbT0zNw2",
    "actionPlanQueryString": "md=bT0yJnNtPTQx0",
    "programQueryString": "md=bT0xMyZzbT00NA2",
    "serviceConfirmationQueryString": "md=bT0xMyZzbT01MQ2",
    "blanketQueryString": "md=bT0xMyZzbT01MA2",
    "moduleScope": "",
    "encryptedBPC": "YnBjPTcwMDIxNzA00",
    "encryptedBlankDocument": "ZGM9MCZicGM9NzAwMjE3MDQ1",
    "Cluster": "us2",
    "App_Key": "b31f590761fafc2f1fbc"
  },
  "TypeOfUser": 1,
  "allowedModulesList": null,
  "DocumentCode": 14485,
  "DocumentTypeId": 31,
  "SMART2DocTypes": "6,7,8,14,19,12,5,9,31,39",
  "IsBuyerAdmin": false,
  "EncryptSupplierDD": "ZGM9MTI2NjgmYnBjPTcwMDIxNzA00",
  "ContactPASDefault": null,
  "SearchScope": "RFX,Auction,Contract,Forms,Scorecards,Order,Invoice,CreditMemo,ReturnNote,ServiceConfirmation,ASN",
  "SearchRESTEndpoint": "",
  "search": null,
  "IsNewSearch": false,
  "IsESEnable": false,
  "ScriptVersion": "0.0.43",
  "encryptedBlankDocument": "ZGM9MCZicGM9NzAwMjE3MDQ1",
  "EncryptedParamBPC": "YnBjPTcwMDIxNzA00",
  "childNodes": null,
  "UserCountryCultureInfo": "en-US",
  "IsRuleEngineAccess": false,
  "IsSmartSetupAdmin": false,
  "UnReadAnnouncementsCount": 0,
  "TaskCardSeq": null,
  "DocTypesCardSeq": null,
  "offset": -4.0,
  "IsLangulageTemplateEnable": false,
  "IsClauseLibraryTemplateEnable": false,
  "AdvSearchDefaultFiltersForAllModules": null,
  "ClientName": null,
  "UserName": null,
  "IsMassUpdateOrder": false,
  "IsManageSecondTierSupplierEnable": false,
  "IsMouseFlowEnabled": false,
  "JWToken":"VdZG9Nd+CMJA6UVBAxPSE5eFdNt3lfJc6CkbmWs1m21CWxlkyCkTkp0*2YbP*U3GiPr*9AI92l3TEJ9Llagf7uBdVV*C7FNMdtKMK+Z9bLypKxp86crhKqOfGaGvSnL2*+KjxFeg2KoWSbTWXDGKbj0tjwkvkpuvo67X3sp+rsWHUhr*JxnO8mAAuOwSt3ipmzSVhywhwVzFt*5dl*2j5IsR9z5VF53e77WUQA8R60rptmJSUpiqJDT0a*VjZspiD6908u5ys76qNSlumxLNdp6WkeCtAhDPZx1tCo1iCBaH2NzRm3uTf51KqcYNqIThmCBdqak5mWOrgeV44wbhKRxyf1YAsJ1mM5dSPq0GEGRzRsZkqj6F45f5NN6U*sHugjnrgPwLwyN7u12fVNg+WUdggTHbiy82g0m9qUKK*fuJOBlNdsQDkzSAhZ3QNHR5tHzAdI9HqeeXNwrJtQICkdoLSFTp283PEz+ZcKMizHuFYSR7hCKdowQZSxagbVgbXVljOGfTEC6XgcrnSDo3JhkJqLjKM8eIuB8yo3j5kHHC3ZKdyjGe10ZwniVAxe2h7DW9jVbO8Pgfrz7UIocVqw6ntTAUl5LDBK88lmI*ya2b5vmzayz2VX8OuHJRZRsAIbbN3aPZVkX+AHCN2LM2vx4aWCXsqCgvhVVNudYlbvvvMeDqGGPrmJUP73sTF*nhaAKdrTFllmCU8v*FM3JhP6nE6Okusp2*2zhwpd4mozIF4mYfCzCfqCY0v9mw*fLvHIfJydOCL+CCi7VP1DDbJQKpaB*ReyidRkPtrxX2Il0mfuc6qRcsMfGQJv+DeKly2GGZ1F6S8jPfhD*wTNRSMAqXuOvrbcw7QD0tDgwqEpKUHC7cdq9IRQ8rY2ZViHeOEUpWgewGF6JLFalxyBUZV6cVj84KoSEEW2Bbzf8ejkg00XEWF5*S*R9f1V5s4MulB+cOL+FNgVGljt03Dp4h3PHpVDiGDiO*tAoMHG5MCDplT0CLNGYzG7PaJ9CCDAgtqwy3BhfHN*CKTzwEl8gZwIr0pSy17Xtqs33NGi9Pfj64RMzy9El5eylxNpS3T5xPChqGfpPOFEc7sYhd3g2IqsLqzZFIGx2dtycGn7xGsUF3aZRUM0WDLQ*I1ZaGy4+6lYU81+ve6AqSpILFtIlxu4U85Im9YwVk8IC+So4ItwJ7mW7DFDDmE*f63Y9cmL7JIQ5hRouOHslIBXg5nqoSWFzLDDw3uL*hwdediXl*nG*esa2g0iLzOj+vINb4aPU391xMQieOMngImCQ6zONcFNf4xIGic9v*WVCLF578kdLMGn97b*yzGLUwdnz70cWXSS0ZTzoCB70IS6Ao19hQni+RSe9YMEU0zvfetJSQ7+7JWBYrIo53TGJM8oy*iGKBaPG0gOZmDQOhe8N3S+md0bGHNYJF60CLwrwqj8flGE*gFJqKHwAajCX6LXWy8jpisMp1mxCG0RJyEo*2wrwdaJGR3EzkRtbLN0UjL7O6BVL5ElR+349n39oeg86aRty1h7mdXOl97o4JGxEnHbkJSGrcwgpcFjBpaDV8YkqIcYUSgp48gtKfNYdyRVy+F7Y7RW4L9AYN4FC3KbxXdwC6Bt+a*HBtXddYUUWihHdFanQYlqY+UwAV1mL0*6tkCK6iY8FIQND*S5anduS*LHl4ZTU*FBZGA7m2srWkk19hI8GNLh6scDACPM02XQYOs5s*cqvsv*930EDK7kJPnosm0KwGO5iZPS9fqFItjH*hhbKSvizaGUwRSGYfVvmq2kuTWfHh7+GuUsmEquXtinmVE7GiOqruvNHhW4g7SMXykEjRWujbtwd9KWqHctGUXd3QTOKA3GbmnDW5bduSjKEXH+dGTR1gQbjEPAPfG1RbKhP0TA2PUrTFwmQ6VRUuI**ndIV2bMH+fIYAiI7aEhlP7rLbiXAL6EzvrA5GZxVNIH*Da4J1acoKkUTGhJguIqgIPBps50P0er34uC2kQzS73Zy7ZWdUPQzEYB8eibb9lhndLX*oXEL7Wdrw2QW0lTGqpLBHpK5dq8tfKA2m88hu+HLV7FcSA11sZppg+7YLAwGj65+F+HPLi6vDyCL*CEgJuSECtfLdKlwCVGrIGDyGqkodjGf3ORZn8YJFLYR+TfRJHoQjXPiuQ6twDigqwiBRz3fwWFv754gLVlZdOsw*DunS7+Efqf9RhNrPzVP5+BWzRodwVBu6pyHreexNWJgwyf54N2P02xPhNo75NmqTDiJv9SMWxh6PCm5L0WdRSmm6iQkxBZovzjCxptGWNt9PsbSC8Cb0ML63JBhIRzGgpQKbQGGUCFk6NPDHu1puOwyPrCIar4rp56+ZBmmumx2pib2*bp2tWmKxu6Aoa8nkNQ4*NCQTRNgsmrJDyfK*qjDhYEArhbJJzG8Z8YAE8kV06zut4VDp5PgOKwYu1U0Klg4VBmijqFbgKV1ubnQRmHxY+kaPyrU9LEI+bEXUub*fjcdMrClD3K+2I7RCgritcZFN7W5Zs4X7Fn3R0+ieDxIWzWsQQ3Zp*TjMzPmzBBW+uPddKtpE3hf4rEDcf9YVgbRpKEN*2FFr2WxjqvKR44xg4caSnNh31kkjORYczk1K8ycI3QDXW*MaNmud7+pCanezfJa1UVuBcZ4bOOCEfwgVkxtNalYXv8zg*TCHkvRf3OrW8KmXJYKU2xyKQv8ISAYz1ajYhruItQj6ukeGjC2wg5yQ*2WFEi1Ph+zm2IbSQ3zs6XkU*Ljbd15daykJwbiu85O*1dBWXoHbZmC+g+7cPRGQ7SWCcaZ656E*1+p*U5+cYVPLeMWNxNXxTy9YJPhjemtLzsm*sKUHR7L0gBLB7qLnlvHAFaxztX+RR66xq7NwxWhY9uaEgEu8pWUrqXWOI8t*6b7AoD6vOkiNbCpCVRBNxNKgI3JXVchnRk2OUXpUECMVLQLthOz247FVIBncMVj8C5ODj0M8P8jGNfCBbEEIMHq2zzEWA9+ye6KHuHQgLKxQYswo+18E40ul3Wp1Wu*nLNxQ1J64g57VBFc5MTo5Tkpahoht1cAD9TDZNY*CRD2cQH0*SCxRBmTUQ1fix8Pfpn21GNo2YiEjzlzG1UPMgFOD23hCJyuia*tXXIp26uL*p6MdboJJKA6+Wa1VKcWN0EFfqfMjRZ7VrKGJWq6Uf8kXruZO0P+e7dpR50CFHDZ6EoNUS4nMiV28AMlfZd8XyI3lkD4*n78y1IKFfhYlugib6IVw7Z4YauTe43guyRpbV2CRt2Q4WnR7oD+c3UoP+xJDzrhR*KmsHtaNGXTQoU72qqB0dji3d3aW0*NhhKiBR5hfS7P4gwckf8zQH0AI8FSw8l4qO7e+SvwDjhXNRdd0aTC8QIovkga7j97VibRWkrN8jrGPWiQ5YLVxKZWnsCQT3gFoQP9We6PO7cHJAhBTKkVZIeYyLmLFS3rCdmJcUYgbzLzqkG3lslmw5HBGPRlh1QpW*IOR6o8DKakzz+FV5ecmpH6zlinlXrQ1gv3WgNTxkS3QLojJYUrJda9TyP4U4C5pjWNqMz7AbqfnP3VSijCToyLQbWSsXqDS7YIaR2F0ww5ylN8C9Ack23IoGQ+7YrsP8cx0OUAdxdc6J9K1SRfwg7Iw6ip1",
  "ActiveSessionDuration": 120,
  "APIMSubscriptionKey":"2e0329d00df24eb8a1672c9b10bf7e16",
  "SCAPIMSubKey": "af529a98950b4d92a1d012f2ca96b738",
  "AccessDetails":{"HasViewReportActivity":true,"HasEditReportActivity":true,"HasViewOpportunityFinderActivity":false,"HasEditOpportunityFinderActivity":false,"HasViewVisionDashboard":true,"HasEditVisionDashboard":true,"HasInsightsAdminActivity":false,"HasNavigateFromSIPToReportsActivity":false,"HasViewOpportunityFinder":false},
  "IsNextGen":true,
};
// window['__cdnPath'] = "https://smartqccdn.azureedge.net/";